import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../desk-v07.js',import.meta.url),'utf8');
let calls=0;
const listeners={};
const state={activePage:'overview',pages:[{id:'overview',modules:[]}]};
const window={DeskBridge:{getState:()=>state,save:()=>{}}};
const document={addEventListener:(name,fn)=>{listeners[name]=fn},querySelector:()=>null,querySelectorAll:()=>[]};
const context={window,document,Intl,Date,URL,AbortSignal,console,
 fetch:async url=>{calls++;assert.match(url,/api.frankfurter.dev\/v2\/rate\/SGD\/USD/);return {ok:true,json:async()=>({base:'SGD',quote:'USD',date:'2026-10-09',rate:0.78})};}};
vm.runInNewContext(src,context);
const api=window.DeskV07;
assert.ok(api);
assert.equal(api.MARKETS.length,6);
assert.match(api.render({id:'abc',type:'markets',config:{markets:['SGX','NYSE']}}),/Singapore Exchange/);
assert.doesNotMatch(api.render({id:'abc',type:'markets',config:{markets:['SGX']}}),/class="v07-market-row" data-v07-exchange="NYSE"/);
assert.match(api.render({id:'xyz',type:'fx',config:{base:'SGD',quote:'USD',amount:100}}),/Convert/);
const sg=api.MARKETS.find(m=>m.id==='SGX');
const ny=api.MARKETS.find(m=>m.id==='NYSE');
assert.equal(api.marketStatus(sg,new Date('2026-10-12T02:00:00Z')).active,true,'Singapore 10am Monday');
assert.equal(api.marketStatus(sg,new Date('2026-10-12T04:30:00Z')).active,false,'SGX midday recess');
assert.equal(api.marketStatus(sg,new Date('2026-10-10T02:00:00Z')).active,false,'SGX weekend');
assert.equal(api.marketStatus(ny,new Date('2026-10-12T14:00:00Z')).active,true,'NY 10am DST');
assert.equal(api.marketStatus(ny,new Date('2026-12-14T15:00:00Z')).active,true,'NY 10am EST');
assert.equal(api.marketStatus(ny,new Date('2026-12-13T15:00:00Z')).active,false,'NY Sunday');
const first=await api.loadFx('SGD','USD'),cached=await api.loadFx('SGD','USD');
assert.equal(first.rate,.78);
assert.equal(first.date,'2026-10-09');
assert.equal(cached.rate,.78);
assert.equal(calls,1,'Rates use cache instead of repeated requests');
assert.equal((await api.loadFx('SGD','SGD')).rate,1);
await assert.rejects(api.loadFx('ZZZ','USD'),/Unsupported/);
assert.ok(!('token' in window),'No privileged token');
assert.match(src,/Indicative regular sessions only/);
assert.match(src,/Published dates can lag/);
console.log('PASS: six global markets, timezone/DST session calculations, FX conversion and caching, source labels, no secrets');
